lr2/lr2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('questionnaire/', include("questionnaire.urls"))
]

lr2/questionnaire/urls.py
from django.urls import path
from .views import list_qest, polls_view, result_view
app_name = "questionnaire"
urlpatterns = [
    path("", list_qest, name="list_qest"),
    path("poll/<int:poll_id>/", polls_view, name="polls_view"),
    path("result/<int:poll_id>/", result_view, name="result_view"),
]

lr2/questionnaire/models.py
from django.db import models
from django.db.models import Count
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import Sum

QUESTION_TYPES = (
        ('single_choice', 'Одиночный выбор'),
        ('multiple_choice', 'Множественный выбор'),
        ('open', 'Открытый вопрос'),
    )
class Poll(models.Model):
    poll_title = models.TextField(max_length=50, null=False, blank=True)
    completed_count = models.IntegerField(default=0)
    def __str__(self):
        return self.poll_title

class Question(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    question_text = models.TextField(max_length=100, null=False, blank=True)
    question_type = models.CharField(max_length=20, choices=QUESTION_TYPES)
    def __str__(self):
        return self.question_text
    def save(self, *args, **kwargs):
           super().save(*args, **kwargs)
           if self.question_type == 'open':
               Choice.objects.create(question=self, choice_text=None)
           elif self.question_type in ['multiple_choice', 'single_choice']:
               Choice.objects.create(question=self, choice_text=None)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.TextField(max_length=100, null=True, blank=True)
    answer_count = models.IntegerField(default=0)

    def __str__(self):
        return str(self.choice_text)
    def get_percentage(self):
        total_count = self.question.choice_set.aggregate(Sum('answer_count'))['answer_count__sum']
        if total_count:
            percentage = (self.answer_count / total_count) * 100
            return round(percentage, 2)
        return 0
    def get_choice_text(self):
        if self.choice_text is None:
            return "Не определились с ответом"
        return self.choice_text

lr2/questionnaire/forms.py
from django import forms
from questionnaire.models import Choice, Question

class PollForm(forms.Form):
    def __init__(self, poll, *args, **kwargs):
        super().__init__(*args, **kwargs)
        questions = poll.question_set.all()
        for question in questions:
            if question.question_type == 'open':
                self.fields[f'question_{question.id}'] = forms.CharField(
                    label=question.question_text,
                    widget=forms.Textarea,
                    required=False  # Set the field as optional
                )
            elif question.question_type == 'multiple_choice':
                choices = question.choice_set.exclude(choice_text=None)
                self.fields[f'question_{question.id}'] = forms.MultipleChoiceField(
                    label=question.question_text,
                    choices=[(choice.id, choice.choice_text) for choice in choices],
                    widget=forms.CheckboxSelectMultiple,
                    required=False  # Set the field as optional
                )
            elif question.question_type == 'single_choice':
                choices = question.choice_set.exclude(choice_text=None)
                self.fields[f'question_{question.id}'] = forms.ChoiceField(
                    label=question.question_text,
                    choices=[(choice.id, choice.choice_text) for choice in choices],
                    widget=forms.RadioSelect,
                    required=False  # Set the field as optional
                )

    def save_answers(self):
        for name, value in self.cleaned_data.items():
            if name.startswith('question_'):
                question_id = int(name.split('_')[1])
                question = Question.objects.get(id=question_id)
                if question.question_type == 'open':
                    if value:
                        existing_answer = Choice.objects.filter(question=question, choice_text=value).first()
                        if existing_answer:
                            existing_answer.answer_count += 1
                            existing_answer.save()
                        else:
                            Choice.objects.create(question=question, choice_text=value, answer_count=1)
                    else:
                        null_choice = question.choice_set.filter(choice_text=None).first()
                        if null_choice:
                            null_choice.answer_count += 1
                            null_choice.save()
                elif question.question_type in ['multiple_choice', 'single_choice']:
                    choices = question.choice_set.exclude(choice_text=None)
                    selected_choices = choices.filter(id__in=value)
                    for choice in selected_choices:
                        choice.answer_count += 1
                        choice.save()
                    if not selected_choices.exists():
                        null_choice = question.choice_set.filter(choice_text=None).first()
                        if null_choice:
                            null_choice.answer_count += 1
                            null_choice.save()

lr2/questionnaire/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpRequest, HttpResponseRedirect
from django.urls import reverse
from questionnaire.forms import PollForm

from questionnaire.models import Poll

def list_qest(request: HttpRequest):
    context = {
        'polls': Poll.objects.all()
    }
    return render(request, 'questionnaire/listQest.html', context=context)

def polls_view(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    if request.method == 'POST':
        form = PollForm(poll, request.POST)
        if form.is_valid():
            form.save_answers()
            return redirect('questionnaire:result_view', poll_id=poll_id)
    else:
        form = PollForm(poll)
    context = {
        'poll': poll,
        'form': form
    }
    return render(request, 'questionnaire/polls.html', context=context)

def result_view(request: HttpRequest, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    questions = poll.question_set.all()
    context = {
        'poll': poll,
        'questions': questions
    }
    return render(request, 'questionnaire/result.html', context=context)

lr2/questionnaire/templates/questionnaire/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head%}

    {% endblock%}
    <title>
        {% block title %}
        
        {% endblock  %}
    </title>
</head>
<body>
    {% block body %}
    Base body
    {% endblock %}
</body>
</html>

lr2/questionnaire/templates/questionnaire/listQest.html
{% extends "questionnaire/base.html" %}
{% block head%}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'questionnaire/css/listQest.css' %}">
{% endblock head %}
{% block title %}
    СУПЕР-МЕГА ОПРОСНИКИ! ПИЦЦА АРРИВА ПО ПРОМОКОДУ RECRENT23 В ДОДО ПРИ ЗАКАЗЕ ОТ 999руб
{% endblock title %}
{% block body %}

<main>
  <h1>Список опросников</h1>
  <ul>
    {% for poll in polls %}
      <li>Опросник по теме: <a href="{% url 'questionnaire:polls_view' poll.id %}">{{ poll.poll_title }}</a></li>
    {% endfor %}
  </ul>
</main>



{% endblock body %}

lr2/questionnaire/templates/questionnaire/polls.html
{% extends "questionnaire/base.html" %}
{% block head%}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'questionnaire/css/polls.css' %}">
{% endblock head %}
{% block title %}
  Опросник по {{ poll.poll_title }}!
{% endblock title %}
{% block body %}
<main class="main">
  <div class="title"><h1>{{ poll.poll_title }}</h1></div>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
  </form>
  <a href="{% url 'questionnaire:result_view' poll.id %}" class="link">Результаты опросника по {{ poll.poll_title }}</a>
</main>

{% endblock body %}

lr2/questionnaire/templates/questionnaire/result.html
{% extends "questionnaire/base.html" %}
{% block head%}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'questionnaire/css/result.css' %}">
{% endblock head %}
{% block title %}
    Результаты
{% endblock title %}
{% block body %}
<main class="block-main">
  <h1 class="title">Результаты по опроснику {{ poll.poll_title }}</h1>
  {% for question in questions %}
    <h3>{{ question.question_text }}</h3>
    <ul>
      {% for choice in question.choice_set.all %}
        <li>{{ choice.get_choice_text }}: {{ choice.get_percentage }}%</li>
      {% endfor %}
    </ul>
  {% endfor %}
  <a href="{% url 'questionnaire:list_qest' %}" class="link">Пройти новый опросник!</a>
  </br>
  <a href="{% url 'questionnaire:polls_view' poll.id %}" class="link">Пройти опрос ещё раз!</a>
</main>




{% endblock body %}